---
version: 1

name: prometheus-simplehttp-exporter
description: Prometheus exporter for simplehttp
homepage: https://prometheus.io/

maintainer: Recipes Maintainers <recipes@mkdeb.sh>

source:
  url: https://github.com/happn-app/prometheus-simplehttp-exporter/archive/v{{ .Version }}.tar.gz
  strip: 1

control:
  depends:
  - python-prometheus-client
  - adduser
  - daemon
  - libc6

  description: |
    Prometheus exporter for simplehttp,
    written in Python with pluggable metric collectors.
  section: net

install:
  recipe:
    /etc/default:
    - pattern: default
      rename: prometheus-simplehttp-exporter
      conffile: true
    /etc/init.d:
    - pattern: init
      rename: prometheus-simplehttp-exporter
      conffile: true
  upstream:
    /etc/prometheus/simplehttp-exporter:
    - pattern: config.yaml
      conffile: true
    /usr/bin:
    - pattern: prometheus-simplehttp-exporter

dirs:
- /var/log/prometheus

# vim: ts=2 sw=2 et
